# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://tonysproducemarket.com
title: Tony's Produce Market
email: fakegmailaccount@fakegmail.com
author: Eric Alford
description: > # "Write an awesome description for your new site here. 
  Tony's Produce Market - A small produce market in Crystal River, FL." 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: google
    displayname: email
    url: mailto:fakegmailaccount@fakegmail.coxm
  - title: facebook
    displayname: facebook
    url: https://facebook.com
  - title: yelp 
    displayname: yelp
    url: https://www.yelp.com

exclude: [vendor]
